databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: dyneems
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: postgresql://test:xGPZlM1pE43JsFLeP16BrJuizHVlsNj8@dpg-cpqshr6ehbks738h0750-a.oregon-postgres.render.com/db_2f9g
        fromDatabase:
          name: educonnect-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4