# Generated by Django 4.2.14 on 2024-07-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=147118, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
