# Generated by Django 4.2.14 on 2024-07-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_department_customuser_initials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=490146, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
