# Generated by Django 4.2.14 on 2024-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pfp',
            field=models.TextField(default='https://i.ibb.co/R932cKN/logo.png'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=383496, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
