# Generated by Django 4.2.14 on 2024-07-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='app.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='initials',
            field=models.CharField(default='', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=730114, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
