# Generated by Django 4.2.14 on 2024-07-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customuser_id_alter_customuser_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=265346, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
