# Generated by Django 4.2.14 on 2024-07-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_customuser_team_lead_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=827829, primary_key=True, serialize=False, unique=True),
        ),
    ]
