# Generated by Django 4.2.14 on 2024-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=282319, primary_key=True, serialize=False, unique=True),
        ),
    ]
