# Generated by Django 4.2.14 on 2024-07-31 22:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_customuser_display_team_lead_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=544359, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ProgReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=500)),
                ('report_description', models.TextField()),
                ('time_spent', models.IntegerField()),
                ('date_submitted', models.DateTimeField(default=datetime.datetime(2024, 7, 31, 15, 29, 40, 593992))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='app.task', verbose_name='task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proguser', to=settings.AUTH_USER_MODEL, verbose_name='proguser')),
            ],
        ),
    ]
