# Generated by Django 4.2.14 on 2024-08-02 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_customuser_id_progreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreport',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=399313, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='progreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='progreport',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='app.task', verbose_name='task'),
        ),
    ]
