# Generated by Django 5.0.7 on 2024-08-13 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_progreport_report_url_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SP_dict', models.CharField(max_length=100000, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=791405, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='progreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
